[release]
addon_name = anki-same-key-show-and-rate
default_output_dir = U:\voothi\20260615234828-anki-same-key-show-and-rate\dist
python_version = 3.13
python_interpreter = 
vendor_dir = vendor

[vendor]
packages = 

# Format: platform_tag = dir_name
[platforms]
macosx_11_0_arm64 = darwin_arm64
macosx_10_15_x86_64 = darwin_x86_64
win_amd64 = win32
manylinux2014_x86_64 = linux

[exclusions]
root_files = 
    meta.json
    .gitignore
    .gitattributes
    pytest.ini
    README.md
    requirements.txt
    release-notes.md

dir_names = 
    user_files
    __pycache__
    .git
    .vscode
    .idea
    .pytest_cache
    tests
    scripts
    dist

[pipeline]
# The steps to run in sequence during release generation.
# 'pytest' is a special keyword to execute python -m pytest.
# Other items are assumed to be python scripts located in this folder.
steps =
    setup_local_vendor.py
    pytest
    create_addon_zip.py
